import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./custom.css";
import ClientLayout from "./ClientLayout";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Care",
  description: "Generated by create next app developed by 3rudit3",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={interFont.variable}>
        <ClientLayout>
          {children}
          </ClientLayout>
      </body>
    </html>
  );
}
